/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bookmark = IDL.Record({
  'verse' : IDL.Nat,
  'book' : IDL.Text,
  'text' : IDL.Text,
  'chapter' : IDL.Nat,
});
export const Note = IDL.Record({
  'verse' : IDL.Nat,
  'book' : IDL.Text,
  'note' : IDL.Text,
  'chapter' : IDL.Nat,
});
export const Progress = IDL.Record({ 'book' : IDL.Text, 'chapter' : IDL.Nat });

export const idlService = IDL.Service({
  'addBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addNote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getProgress' : IDL.Func([], [IDL.Opt(Progress)], ['query']),
  'removeBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'updateProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bookmark = IDL.Record({
    'verse' : IDL.Nat,
    'book' : IDL.Text,
    'text' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  const Note = IDL.Record({
    'verse' : IDL.Nat,
    'book' : IDL.Text,
    'note' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  const Progress = IDL.Record({ 'book' : IDL.Text, 'chapter' : IDL.Nat });
  
  return IDL.Service({
    'addBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addNote' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getProgress' : IDL.Func([], [IDL.Opt(Progress)], ['query']),
    'removeBookmark' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'updateProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };